# Generated by Django 4.1.13 on 2024-11-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="상세주소",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="detail_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
