# Generated by Django 4.1.13 on 2024-11-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_remove_contactinfo_상세주소_contactinfo_detail_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="common.user",
            ),
        ),
        migrations.AlterField(
            model_name="registrationinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="common.user",
            ),
        ),
        migrations.AlterField(
            model_name="securityinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="common.user",
            ),
        ),
    ]
