# Generated by Django 4.1.13 on 2024-11-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_contactinfo_user_alter_registrationinfo_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
