# Generated by Django 4.1.13 on 2024-10-30 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.JSONField()),
                ('time', models.PositiveIntegerField()),
                ('intention', models.TextField()),
                ('summary', models.TextField()),
                ('making_description', models.TextField()),
                ('target_funding', models.PositiveIntegerField()),
                ('funding_description', models.TextField()),
                ('funding_deadline', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('total_funding_amount', models.PositiveIntegerField(default=0)),
                ('backers', models.JSONField(default=list)),
                ('payment_history', models.JSONField(default=list)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
