# Generated by Django 4.1.13 on 2024-11-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingmovie",
            name="movie_file_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fundingmovie",
            name="poster_file_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
