# Generated by Django 4.1.13 on 2024-10-30 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.JSONField()),
                ('time', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('release_date', models.DateField()),
                ('streaming_url', models.FileField(upload_to='movies/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('payment_history', models.JSONField(default=list)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewed_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
